pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
metadata:
    name: python
spec:
    containers:
    - name: python
      image: python:slim
      command:
      - cat
      tty: true
      securityContext:
          privileged: true
'''
        }
    }

    environment {
        AWS_DEFAULT_REGION = 'us-east-1'
        AWS_ACCOUNT_ID = '511620223753'    // Replace with your AWS account ID
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '3'))
        durabilityHint('PERFORMANCE_OPTIMIZED')
        disableConcurrentBuilds()
    }

    stages {
        stage('Build with Podman') {
            steps {
                withCredentials([aws(credentialsId: 'AWS_CLI_CREDENTIALS')]) {
                    container('python') {
                        sh '''
                            apt update -y && apt install -y podman awscli git
                            echo "The job name is ${JOB_NAME}"
                            cd ${WORKSPACE}
                            ls
                            ls -lthr
                            git clone https://github.com/quickbooks2018/terraform-k8s-Jenkins-podman-buildah.git
                            cd terraform-k8s-Jenkins-podman-buildah
                            ls
                            cd build && cp ${WORKSPACE}/terraform-k8s-Jenkins-podman-buildah/docker/Dockerfile .
                            echo "jenkins build Number is ${BUILD_NUMBER}"
                            podman build -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/devops:${BUILD_NUMBER} -f Dockerfile .
                            podman images
                            aws ecr get-login-password --region $AWS_DEFAULT_REGION | podman login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
                            podman push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/devops:${BUILD_NUMBER}
                        '''
                    }
                }
            }
        }
    }
}
